import logging
import os
import tempfile
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from zotero_cli.core.interfaces import ZoteroGateway

logger = logging.getLogger(__name__)

# Attachments whose file is stored in Zotero (uploaded, or saved by the
# Connector from a web page) and can be downloaded through the Web API.
_STORED_FILE_MODES = ("imported_file", "imported_url")


@dataclass
class TransferResult:
    new_key: Optional[str]
    copied_children: int = 0
    failures: List[str] = field(default_factory=list)
    source_deleted: bool = False

    @property
    def complete(self) -> bool:
        return self.new_key is not None and not self.failures


class TransferService:
    """Service for moving items between different Zotero libraries."""

    def transfer_item(
        self,
        item_key: str,
        source_gateway: ZoteroGateway,
        dest_gateway: ZoteroGateway,
        delete_source: bool = False,
    ) -> TransferResult:
        """
        Copies an item (metadata, notes and stored files) from the source to
        the destination library.

        With `delete_source`, the source is deleted ONLY if every child was
        copied: a failed note or file copy, or a child that can't be copied
        (a linked file on someone's disk, a link-only attachment), leaves
        the source in place (Issue #396). Before, failures were only logged
        and the source was deleted anyway, losing those files.
        """
        source_item = source_gateway.get_item(item_key)
        if not source_item:
            logger.error(f"Source item {item_key} not found.")
            return TransferResult(new_key=None, failures=[f"source item {item_key} not found"])

        dest_item_data = source_item.raw_data.get("data", {}).copy()
        # Keys that are library-specific or regenerated by the destination.
        for key in ["key", "version", "library", "collections", "relations"]:
            dest_item_data.pop(key, None)

        new_item_key = dest_gateway.create_generic_item(dest_item_data)
        if not new_item_key:
            logger.error("Failed to create item in destination library.")
            return TransferResult(new_key=None, failures=["could not create the destination item"])

        logger.info(f"Created item {new_item_key} in destination library.")
        result = TransferResult(new_key=new_item_key)

        for child in source_gateway.get_item_children(item_key):
            failure = self._copy_child(child, source_gateway, dest_gateway, new_item_key)
            if failure:
                result.failures.append(failure)
                logger.warning(failure)
            else:
                result.copied_children += 1

        if delete_source:
            if result.failures:
                logger.warning(
                    f"Keeping source item {item_key}: {len(result.failures)} child(ren) not copied."
                )
            elif source_gateway.delete_item(item_key, source_item.version):
                result.source_deleted = True
                logger.info(f"Deleted source item {item_key}")
            else:
                result.failures.append(f"could not delete source item {item_key}")

        return result

    @staticmethod
    def _copy_child(
        child: Dict[str, Any],
        source_gateway: ZoteroGateway,
        dest_gateway: ZoteroGateway,
        new_item_key: str,
    ) -> Optional[str]:
        """Copies one child; returns a failure description, or None."""
        data = child.get("data", {})
        child_key = child.get("key") or data.get("key") or "?"
        item_type = data.get("itemType")

        if item_type == "note":
            if dest_gateway.create_note(new_item_key, data.get("note", "")):
                return None
            return f"note {child_key} was not copied"

        if item_type != "attachment":
            return f"child {child_key} ({item_type}) can't be transferred"

        link_mode = data.get("linkMode")
        if link_mode not in _STORED_FILE_MODES:
            # linked_file points at a path on someone's disk, linked_url at a
            # web page: neither has a file the Web API can hand over.
            return f"attachment {child_key} ({link_mode}) can't be transferred"

        # The filename comes from library data: keep only its last path
        # component so it can't point outside the temp directory.
        filename = os.path.basename(str(data.get("filename") or "")) or "attachment"
        mime_type = data.get("contentType", "application/octet-stream")
        with tempfile.TemporaryDirectory() as tmp_dir:
            local_path = os.path.join(tmp_dir, filename)
            if not source_gateway.download_attachment(child_key, local_path):
                return f"attachment {child_key} ({filename}) could not be downloaded"
            if not dest_gateway.upload_attachment(new_item_key, local_path, mime_type=mime_type):
                return f"attachment {child_key} ({filename}) could not be uploaded"
        return None
